project:
  type: website
  output-dir: docs

website:
  title: "PSTAT 100: Spring 2024"
  favicon: "Images/Logos_Icons/hex_second_pass.svg"
  sidebar: 
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: Pages/policies.qmd
        text: Policies
      - href: Pages/materials.qmd
        text: Materials
      - section: "Labs"
        contents:
          - section: "Lab00"
            contents:
              - href: Labs/Lab00/intro2r.qmd
                text: "Intro to `R`"
              - href: Labs/Lab00/df_basics.qmd
                text: "Dataframe Basics"
      - href: Pages/staff.qmd
        text: Course Staff
    logo: "Images/Logos_Icons/hex_second_pass.svg"
    title: "PSTAT 100: Spring 2024"

format:
  html:
    theme:
      light: [sandstone, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true



