project:
  type: website
  output-dir: docs

website:
  title: "PSTAT 100: Summer 2025"
  favicon: "Images/Logos_Icons/hex.svg"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - text: "{{< fa circle-info >}} Course Info"
        menu:
          - href: "Pages/Info/policies.qmd"
            text: "{{< fa gavel >}} Policies"
          - href: "Pages/Info/staff.qmd"
            text: "{{< fa people-group >}} Course Staff"
      - href: "Pages/schedule.qmd"
        text: "{{< fa calendar-days >}} Schedule"
      - text: "{{< fa laptop >}} Lab 00"
        menu:
          - href: "Pages/Lab00/intro2r.qmd"
            text: "{{< fa code >}} Intro to R"
          - href: "Pages/Lab00/df_basics.qmd"
            text: "{{< fa table >}} Dataframe Basics"
          - href: "Pages/Lab00/quarto.qmd"
            text: "{{< fa file >}} Intro to Quarto"
      - href: "Pages/ICAs.qmd"
        text: "{{< fa pencil >}} ICA Info"
      - href: "Pages/projects.qmd"
        text: "{{< fa folder-open >}} Projects"

format:
  html:
    theme: [minty, styles.scss]
    toc: true



