---
title: "Information about ICAs"
page-layout: full
fontsize: 14pt
---


## ICA 02

::: {.callout-important}
## **Reminder**

ICA02 is taking place on **Thursday July 24, 2025** from **12:30 - 1:35 pm** in **Harold Frank Hall 1104** (note that this is **NOT** our usual lecture classroom).
:::

-   **Information Document (PLEASE READ)**: <a href="https://docs.google.com/document/d/1fJ6CSFQzffDzDncQS9zfFD6Lmq6KPho5rma3UoDb-to/" target="_blank"><button type="button" class="btn btn-primary">Link</button></a>
    -   **Note:** The "`R` Cheatsheets" that will be provided are exactly the files that appear on the Course Server, under the `Cheatsheets/` subdirectory. <br /> <br />

-   **Cover Page**: <a href="https://docs.google.com/document/d/1D-YaPNlmQrXY364xpH3elrPlpEqTY53BT08jsUqcu1o/" target="_blank"><button type="button" class="btn btn-primary">Link</button></a>
    -   This is the cover page that will be attached to the ICA on Thursday - I encourage you to read through it now, so you don't have to spend time reading through it during the actual ICA! <br /> <br />
  
-   **Practice Problems**: <a href="https://docs.google.com/document/d/172jHoF2ZuUFRSTyR3f6amctVGThILtjEozxY7UWuVlc/" target="_blank"><button type="button" class="btn btn-primary">Blank</button></a> 
    -   Solutions will not be posted until Tuesday, July 22, 2025.  <br /> <br />
    
    
-   **Spring 2024 ICA02**: <a href="https://docs.google.com/document/d/1NrYly1FHqMTe3ku77ZT0K7NWdABgVByAjj3sGn7dpTc/" target="_blank"><button type="button" class="btn btn-primary">Blank</button></a> 
    -   This is the ICA01 I administered in Spring 2024, when I last taught this course.
    -   Solutions will not be posted until Tuesday, July 22, 2025.
    -   **Important:** Certain problems are out-of-scope, because the order of topics has been changed slightly since Spring 2024. Additionally, the Spring 2024 ICA02 was entirely multiple choice whereas the Summer 2025 ICA will consist of a mix of multiple choice _and_ free response questions (please see the **Information Document** linked above). <br /> <br />
  

---

## ICA 01

-   **Solutions to Version A:** <a href="https://docs.google.com/document/d/1eO2Y0dlMDX77ut00W0rZWbQiFE2hmPixi2icxPEN6zI" target="_blank"><button type="button" class="btn btn-primary">Link</button></a>

-   **Post-ICA Info Document:** <a href="https://docs.google.com/document/d/16RYnqtDUJtehe3Twz-uKVDrTIWuxxVoBPA9-PW1-WH0/" target="_blank"><button type="button" class="btn btn-primary">Link</button></a>
    -   Please read this document **FULLY** before submitting a regrade request.

::: {.callout-important}
## **Reminder**

ICA01 is taking place on **Thursday July 3, 2025** from **12:30 - 1:35 pm** in **Harold Frank Hall 1104** (note that this is **NOT** our usual lecture classroom).
:::

-   **Information Document (PLEASE READ)**: <a href="https://docs.google.com/document/d/18ONudNjYhVJy3x4qAyetUhk_ukvjMSoTFjGqMtPqAXE" target="_blank"><button type="button" class="btn btn-primary">Link</button></a>
    -   **Note:** The "`R` Cheatsheets" that will be provided are exactly the files that appear on the Course Server, under the `Cheatsheets/` subdirectory. <br /> <br />

-   **Cover Page**: <a href="https://docs.google.com/document/d/17Qtu_OtccK_tnIXJEhOjtTk1FBHXye9zB847WNHNybc" target="_blank"><button type="button" class="btn btn-primary">Link</button></a>
    -   This is the cover page that will be attached to the ICA on Thursday - I encourage you to read through it now, so you don't have to spend time reading through it during the actual ICA! <br /> <br />
  
-   **Practice Problems**: <a href="https://docs.google.com/document/d/1WCU1uBHv50QFUGat84q7bN170LsJDP_x4vMTodlhDDw" target="_blank"><button type="button" class="btn btn-primary">Blank</button></a> <a href="https://docs.google.com/document/d/1xr_4EfHeoPV04nRkRGfKfFF7AtQaIy9dmhxFPssL1Yg" target="_blank"><button type="button" class="btn btn-primary">Solutions</button></a>
    -   If you feel there are typos, please leave a comment on the document. <br /> <br />
    
    
-   **Spring 2024 ICA01**: <a href="https://docs.google.com/document/d/14ojmkKA4-nSMRj7kQS44bCQmoQYztYJG93QIfShRNIA" target="_blank"><button type="button" class="btn btn-primary">Blank</button></a> <a href="https://docs.google.com/document/d/1cwUoBQh_LmlWuc_pVHkJoQNfYJse4wXQhDTmNG4k6eg" target="_blank"><button type="button" class="btn btn-primary">Solutions</button></a>
    -   This is the ICA01 I administered in Spring 2024, when I last taught this course.
    -   **Important:** Certain problems are out-of-scope, because the order of topics has been changed slightly since Spring 2024. Additionally, the Spring 2024 ICA01 was entirely multiple choice whereas the Summer 2025 ICA will consist of a mix of multiple choice _and_ free response questions (please see the **Information Document** linked above). <br /> <br />
  

    
