---
title: "Information about Course Projects"
page-layout: full
fontsize: 14pt
---

## Mid-Quarter Project

### Group Formation

As has been stated a few times before, the **Mid-Quarter Project** this quarter **must be submitted in groups**. To ensure you have ample time to work on a project as a group, I am asking that you finalize your group members by no later than **11:59 pm on Tuesday July 1, 2025**. A corresponding Gradescope assignment has been posted as well.

[**<i class="fa-solid fa-file-pdf"></i> Click Here for Further Instructions**](../Files/Projects/Mid_Quarter_Project_Group_Signups.pdf)

### Project Information

**The full project description will be posted sometime during Friday, June 27, 2025.** 

As a brief overview, the Mid-Quarter project is an example of what is sometimes called a **visualization project**; in other words, you will be applying various techniques from **descriptive statistics** to analyze a dataset pertaining to the **United States Census**. The project will touch on the following topics (list is not comprehensive):

-   Joining multiple dataframes (covered in Lab02)
-   Generating appropriate and presentation-quality visualizations (covered in Lectures 3 and 4, and Homework 1)
-   Interpreting visualizations in context (covered in Lectures 3 and 4, and Homework 1)
-   The importance of domain knowlede (that is, I will have you Google some terms related to the dataset to be able to better understand what it is saying in context).

Your project deliverable will be a **report** written in Quarto (like the lab documents), which will need to be submitted by 11:59pm on Sunday, July 13, 2025. We will be providing you with the rubric by which your report will be graded; this will be posted (along with the full project description) on Friday, June 27, 2025.