---
title: "PSTAT 100: Data Science Concepts and Analysis"
subtitle: "Selected Solutions"
author:
  - name: "Ethan Marzban"
    affiliations:
      - name: "Summer Session A, 2025"
author-title: "Instructor"
affiliation-title: "Quarter"
format: html
page-layout: full
fontsize: 14pt
---


::: {.callout-important}
## **Important** 

Below are solutions to selected assignment. Some things to keep in mind:

-   There may be typos, so please proceed with caution (feel free to ask during Office Hours!)
-   There are often many different ways to approach a problem, each of them “correct”! As such, if you work through a problem in a different way than the solutions that’s fine - your way is not necessarily wrong.

:::


## Labs

:::: {.columns}

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab01_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab01</button></a>
:::

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab02_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab02</button></a>
:::

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab03_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab03</button></a>
:::

::::


:::: {.columns}

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab04_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab04</button></a>
:::

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab05_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab05</button></a>
:::

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab06_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab06</button></a>
:::

::::


:::: {.columns}

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab07_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab07</button></a>
:::

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/lab08_solns.pdf" target="_blank"><button type="button" class="btn btn-primary">Lab08</button></a>
:::


::::

-   **Lab04 Note:** There was a typo in Question 9: you were meant to overlay the density over your histogram from Question _8_, not Question _7_. (The grader graded very leniently, as a result.)

-   **Lab07 Note:** I know people had some trouble getting Question 6 to work. In a sense, this was to be expected and one of the reasons why multicollinearity is so dangerous!
    -   For the purposes of an ICA, you should just make sure you're comfortable detecting multicollinearity using a correlation matrix, and be generally aware of some of the implications multicollinearity has on a model (if it is present).


## Homework

:::: {.columns}

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/HW01_Solns.pdf" target="_blank"><button type="button" class="btn btn-primary">HW01</button></a>
:::

::: {.column width="33.3333%"}
-   <a href="../Files/Solns/HW02_Solns.pdf" target="_blank"><button type="button" class="btn btn-primary">HW02</button></a>
:::

::::